# https://help.github.com/en/articles/metadata-syntax-for-github-actions

name: 'Delete last release'
description: 'Delete the repositories last release'
author: 'Janus451'
inputs: 
  github_token: 
    description: 'Take token from workplace environment '
    required: true
  repository:
    description: 'Specify to delete last release of other repository. Default is current repository'
    default: ''
    required: false
runs:
  using: 'node12'
  main: 'index.js'